@startuml
left to right direction
skin rose

entity Biblioteca{}

entity Libro{
  titulo
  autor
  categoria
}

entity Socio{
  nombre
  numero de socio
  libros en prestamo
}

Biblioteca "1" -- "*" Libro
Biblioteca "0..1" -- "1..*" Socio

@enduml
